services:

  db:
    image: mysql
    container_name: todo_db
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: todo_backend
    restart: unless-stopped
    command: gunicorn --reload -w 4 -b 0.0.0.0:8000 app:app
    env_file:
      - ./.env
    develop:
      watch: 
        - path: ./requirements.txt
          action: rebuild
        - path: ./app
          target: /code/app
          action: sync

  nginx:
    image: nginx:latest
    container_name: todo_nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  mysql_data:
